# Site configuration
# https://github.com/daviddarnes/alembic
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
 # - jekyll-default-layout # new
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: CoryMSimon # jekyll-seo-tag > Owners twitter username
author: CorySimon # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: CorySimon # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/CoryMSimon
    - https://github.com/CorySimon

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Musings on science, math, engineering, and the environment." # The post list page content
    feature_text: ""
    feature_image: "../images/OregonCoast.JPG"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "../images/OregonCoast.JPG" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "../images/OregonCoast.JPG" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "The Simon Ensemble" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
description: "The Simon Ensemble at Oregon State University" # Site description and default description, also used in jekyll-seo-tag
 # url: "local" # Site url, also used in jekyll-seo-tag
 # url: http://localhost:4000
url: https://simonEnsemble.github.io
baseurl: ""
 # repo: "https://github.com/CorySimon/alembic"
email: "CoryMSimon@gmail.com"
disqus: "simonensemble" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# see gravitar.com `echo -n myemail@oregonstate.edu | md5sum` (lowercase)
avatarurl: "https://www.gravatar.com/avatar/de74dcd32c1abfb40e07e895346f416d" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub <- hashed email

# 8. Site navigation
navigation_header:
  Research: /
  Publications: /publications/
  Teaching: /teaching/
  People: /people/
  Blog: /blog/
  Join Us: /join/

navigation_footer:
  Research: /
  Publications: /publications/
  Teaching: /teaching/
  People: /people/
  Blog: /blog/
  Join Us: /join/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/CoryMSimon
 #   LinkedIn: https://www.linkedin.com/in/daviddarnes
 #   Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/CorySimon
 #   link: https://darn.es
 #   RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
  #
